on:
  workflow_dispatch:
  
name: Testing devel actions

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:

  pkg-in-subfolder:
    name: Package in subfolder - Bioc ${{ matrix.bioc-version }} (${{ matrix.os }}) 
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-20.04, windows-2022, macos-11]
        os: [ubuntu-20.04]
        bioc-version: [release]
        image: bioconductor/bioconductor_docker:RELEASE_3_14
        
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.image }}
    
    steps:
    
      - uses: actions/checkout@v2
      
      ## We only using Ubuntu and BioC-release here, 
      ## so lets use the Rstudio package manager
      ## to install binary linux packages
      - name: Setup R and Bioconductor
        if: matrix.image == null
        uses: grimbough/bioc-actions/setup-bioc@devel
        with:
          bioc-version: ${{ matrix.bioc-version }}
          bioc-mirror: https://packagemanager.rstudio.com/bioconductor
          
      - name: Set environment variables
        run: |
          ## todays date is use for the cache
          echo "DATE=$(date +%D)" >> $GITHUB_ENV 
        shell: bash
        
      - name: Cache install R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.os }}-${{ matrix.bioc-version }}-${{ env.DATE }}-1
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.bioc-version }}-
          
      - name: Run BiocCheck without arguments
        uses: grimbough/bioc-actions/run-BiocCheck@devel
        with:
          package-directory: 'inst/nestedPKG'
          error-on: 'never'
          

