on:
  workflow_dispatch:
  
name: Nested package

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Testing:
  
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        bioc-version: [release]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - uses: actions/checkout@v2
      
      ## We only using Ubuntu and BioC-release here, 
      ## so lets use the Rstudio package manager
      ## to install binary linux packages
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.bioc-version }}
          bioc-mirror: https://packagemanager.rstudio.com/bioconductor
          
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.os }}-${{ matrix.bioc-version}}-1
          
      - name: Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1
        with:
          package-directory: 'inst/nestedPKG'
      
      ## Run all tests in BiocCheck, include those we know fail
      ## Use the 'error-on' to prevent this failing the workflow
      - name: Run BiocCheck without arguments
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          package-directory: 'inst/nestedPKG'
          error-on: 'never'
          
      ## upload some results files
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-bioc-${{ matrix.bioc-version}}-nested
          path: |
            ${{ steps.build-install-check.outputs.check-dir }}
            ${{ steps.build-install-check.outputs.source-tarball }}
