on:
  push:
  workflow_dispatch:
  
name: Testing Bioc Setup



jobs:
  Testing:
  
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]
  
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v0
        with:
          bioc-version: devel
          
