on:
  workflow_dispatch:
  
name: Top-level package repository

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Testing:
  
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]
        ## Test using both Bioconductor devel and release
        bioc-version: [devel, release]
        #bioc-version: [devel]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - uses: actions/checkout@v2
          
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.bioc-version }}
          bioc-mirror: https://ftp.gwdg.de/pub/misc/bioconductor
          
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ matrix.os }}-${{ matrix.bioc-version}}-2
          
      - name: Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1
        with:
          package-directory: '.'
      
      ## Turn off the checks that we know will fail
      ## Cause the workflow to error if any new errors appear
      - name: Run BiocCheck with arguments
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          package-directory: '.'
          arguments: '--no-check-bioc-views --no-check-vignettes --no-check-bioc-help'
          error-on: 'error'

      ## upload some results files
      - name: Upload check output
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-bioc-${{ matrix.bioc-version}}
          path: |
            ${{ steps.build-install-check.outputs.check-dir }}
            ${{ steps.build-install-check.outputs.source-tarball }}

